name: Deploy Website to Multi-Account S3

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Enables manual triggering
    inputs:
      destroy:
        description: "Set to 'true' to destroy resources."
        required: false
        default: "false"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        account_id:
          - "011624006725"  # Account 1 ID
      fail-fast: false
      max-parallel: 1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Role ARN and Configure AWS Credentials
        run: |
          ROLE_ARN="arn:aws:iam::${{ matrix.account_id }}:role/GitHubOIDCRole"
          echo "ROLE_ARN=$ROLE_ARN" >> $GITHUB_ENV

      - name: Assume IAM Role and Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Select or Create Workspace
        run: |
          terraform workspace select "${{ matrix.account_id }}" || terraform workspace new "${{ matrix.account_id }}"
        working-directory: ./terraform

      - name: Terraform Apply
        if: github.event.inputs.destroy != 'true'
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env: 
          TF_VAR_bucket_name: "my-website-bucket-${{ matrix.account_id }}"

      - name: Export Code to S3
        if: github.event.inputs.destroy != 'true'
        run: aws s3 sync ./app s3://$BUCKET_NAME
        env:
          BUCKET_NAME: "my-website-bucket-${{ matrix.account_id }}"
          AWS_EC2_METADATA_DISABLED: true

      - name: Terraform Destroy
        if: github.event.inputs.destroy == 'true'
        run: terraform destroy -auto-approve
        working-directory: ./terraform
        env: 
          TF_VAR_bucket_name: "my-website-bucket-${{ matrix.account_id }}"
